### ISSUE TITLE
peer-peer code review Week 2

### ISSUE THREAD

**Issue by svitalis123** [AdnanOlarmmi/Demo-Portfolio#10]
## Highlights
- Fantastic code flow.
- Clear commits.
- Passed linters
- Good Github flow

## Issues

please check the following suggestions on how to improve your code.

Please assign a description to the alt property. It improves your code flow and it is a good practice.
- shown in the code below from line 245-

`
	<img class="btm_line" src="images/rectangle-line.svg" alt="">
					<ul class="contactsIcon">
						<li><img src="images/Icons/Vectorgithubicon.svg" alt="" /></li>
						<li><img src="images/Icons/Grouplinkedinicon.svg" alt="" /></li>
`
- Please contact me[@svitalis123 ] for any clarifications and concerns.  Reply me through the issue

**Comment by AdnanOlarmmi** [comment]
Thanks @svitalis123 ...
You're appreciated 🤗
