### ISSUE TITLE
Peer-to-Peer Project review

### ISSUE THREAD

**Issue by adel-gu** [AdnanOlarmmi/Demo-Portfolio#16]
**Hi @ AdnanOlarmmi 👋**
# STATUS: CHANGES REQUIRED 🚨

Such a great job you did 👏👏 however, there are some Notes and suggestions that might help your project stand out and make it to the next level 🚀.

![bravo](https://user-images.githubusercontent.com/68030297/188216073-4b8b1824-cf6c-4d49-8bc7-f72152254a41.gif)

## Highlights: 
- No linter errors ✅
- Followed the Pair-Programing flow 👔
- Animation was applied to the logo 🖼️
- Great commit history  ⏳

## Required Changes ♻️
The paragraph element is used to convey a message and allows the reader to get more information easily.

- [ ]  To achieve a better user experience, I suggest making it simple, and kindly remove the Animation.

https://github.com/AdnanOlarmmi/Personal_Portfolio/blob/6e70bd662d686a36361a9040bc860cfee1fc3b78/styles.css#L330-L332

---

- **Branch:** [animation_and_transition](https://github.com/AdnanOlarmmi/Personal_Portfolio/tree/animation_and_transition)
- **Last tow commits:**
  - [Add rotate function to the logo when page loads](https://github.com/AdnanOlarmmi/Personal_Portfolio/commit/078e62ab39a8aff66c905bd9a05643bdcb0628a7)
  - [Add translate function to the form description](https://github.com/AdnanOlarmmi/Personal_Portfolio/commit/6e70bd662d686a36361a9040bc860cfee1fc3b78)

**Comment by AdnanOlarmmi** [comment]
You are appreciated @adel-gu, thank you so much, all done and rectified. 😃
