### ISSUE TITLE
Morning Session Peer review

### ISSUE THREAD

**Issue by Abe1able** [AdnanOlarmmi/Demo-Portfolio#18]
### Hi @ AdnanOlarmmi 👋

Such a great job you did 👏👏 however, there are some Notes and suggestions that might help your project stand out and make it to the next level 🚀.

### Highlights:

- No linter errors ✅
- Followed the Pair-Programing flow 👔
- Great commit history ⏳

###  Changes ♻️

- Kindly remove commented out code to make your code more readable.
- In my opinion, the spacing on your index.html file can be improved.

**Comment by AdnanOlarmmi** [comment]
@Abe1able, Thank you for the feedback. I shall work on it 🙂
