### ISSUE TITLE
Peer to Peer Code Review - Block 4

### ISSUE THREAD

**Issue by lorenzoworx** [AdnanOlarmmi/Demo-Portfolio#19]
Hi @AdnanOlarmmi 

Good job so far!
There's just one minor change that I would recommend at this point

![](https://media.giphy.com/media/kGXcQp3dWrU44hfnqq/giphy.gif)

## Optional suggestions
- I suggest reducing the indentation in your index.html file for a more cohesive code

**Comment by AdnanOlarmmi** [comment]
Thank you so much @lorenzoworx, all done and rectified 😃
